services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./keycloak_data:/opt/keycloak/data/

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - 5433:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6380:6379

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: yeasir
      MONGO_INITDB_ROOT_PASSWORD: JTsfy876yK9CfDBd
      MONGO_INITDB_DATABASE: test

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
      - keycloak
      - postgres
      - mongo
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      CORS_ORIGIN: http://localhost:4173,http://localhost:5173,http://localhost:8080
      MONGODB_URI: mongodb://yeasir:JTsfy876yK9CfDBd@mongo:27017/
      REDIS_URL: redis://redis:6379
      REDIRECT_URL: http://localhost:5173
      COOKIE_KEY: WSD
      REFRESH_KEY: WSD-REFRESH
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: wsd
      KEYCLOAK_CLIENT_ID: myclient
      KEYCLOAK_ADMIN_USER_NAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_PUBLIC_SERVER_URL: http://localhost:5000/api/v1
    ports:
      - 4173:4173
    depends_on:
      - api
    restart: unless-stopped
    # environment:
    #   VITE_PUBLIC_SERVER_URL: http://localhost:5000/api/v1

volumes:
  keycloak_data:
  postgres_data:
