services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpassword
      - KC_DB_SCHEMA=public
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin=value
    command: ["start-dev"]
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./keycloak_data:/opt/keycloak/data/

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379